version: '3.8'

services:
  ollama-llama3:
    build: "./backend/ollama-llama3"   # custom Dockerfile for llama3
    container_name: ollama-llama3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11435:11434"   # host:container
    volumes:
      - ollama-llama3:/root/.ollama
    networks:
      - quiz-app-network
    restart: unless-stopped

  node-container:
    build: "./backend/node-server"
    container_name: node-container
    ports:
      - "3000:3000"
    depends_on:
      - ollama-llama3
    networks:
      - quiz-app-network
    environment:
      - OLLAMA_HOST=http://ollama-llama3:11434
    restart: unless-stopped

networks:
  quiz-app-network:
    name: quiz-app-network
    driver: bridge

volumes:
  ollama-llama3:
